### PR TITLE
google play tool to get latest build number

### PR DESCRIPTION
**Pull request by BondarenkoStas**
Get latest build from Google Play

### New actions:

- google-play get-latest-build-number

### Global changes:

- document required tool arguments

### Example execution of new actions:

- get from all tracks
```bash
> google-play get-latest-build-number --package-name 'io.codemagic.androidhelloworldapp'
Create an edit for the package "io.codemagic.androidhelloworldapp"
Get information about the track "internal"for the package "io.codemagic.androidhelloworldapp"
Latest version code for internal track: 29
Get information about the track "alpha"for the package "io.codemagic.androidhelloworldapp"
Failed to get version code from Google Play from alpha track. Track not found: alpha.
Get information about the track "beta"for the package "io.codemagic.androidhelloworldapp"
Failed to get version code from Google Play from beta track. Track not found: beta.
Get information about the track "production"for the package "io.codemagic.androidhelloworldapp"
Failed to get version code from Google Play from production track. Track not found: production.
Delete the edit "12033080892927930378" for the package "io.codemagic.androidhelloworldapp"
29
```

- get from all tracks silently
```bash
> google-play get-latest-build-number --package-name 'io.codemagic.androidhelloworldapp' -s
29
```

- get from all tracks with api calls
```bash
> google-play get-latest-build-number --package-name 'io.codemagic.androidhelloworldapp' --log-api-calls
Create an edit for the package "io.codemagic.androidhelloworldapp"

Id: 15599468336025609751
Expiry time seconds: 1614696040
Get information about the track "internal"for the package "io.codemagic.androidhelloworldapp"

Track: internal
Releases: [
        Name: 29 (1.0.29)
        Status: draft
        Version codes: [
                29
        ]

        Name: trying2
        Status: completed
        Version codes: [
                26
        ]
        Release notes: [
                Language: en-US
                Text: trying2
        ]
]
Latest version code for internal track: 29
Get information about the track "alpha"for the package "io.codemagic.androidhelloworldapp"
Failed to get version code from Google Play from alpha track. Track not found: alpha.
Get information about the track "beta"for the package "io.codemagic.androidhelloworldapp"
Failed to get version code from Google Play from beta track. Track not found: beta.
Get information about the track "production"for the package "io.codemagic.androidhelloworldapp"
Failed to get version code from Google Play from production track. Track not found: production.
Delete the edit "15599468336025609751" for the package "io.codemagic.androidhelloworldapp"
29
```

- get from specified tracks
```bash
> google-play get-latest-build-number --package-name 'io.codemagic.androidhelloworldapp' --track internal beta
Create an edit for the package "io.codemagic.androidhelloworldapp"
Get information about the track "internal"for the package "io.codemagic.androidhelloworldapp"
Latest version code for internal track: 29
Get information about the track "beta"for the package "io.codemagic.androidhelloworldapp"
Failed to get version code from Google Play from beta track. Track not found: beta.
Delete the edit "07034644456261452589" for the package "io.codemagic.androidhelloworldapp"
29
```

- get from non-existing app
```bash
> google-play get-latest-build-number --package-name 'io.codemagic.androidhelloworldappp'
Create an edit for the package "io.codemagic.androidhelloworldappp"
Unable to create an edit for package "io.codemagic.androidhelloworldappp". Package not found: io.codemagic.androidhelloworldappp.
```

- get with not existing version codes
```bash
> google-play get-latest-build-number --package-name 'io.codemagic.androidhelloworldapp' --track beta
Create an edit for the package "io.codemagic.androidhelloworldapp"
Get information about the track "beta"for the package "io.codemagic.androidhelloworldapp"
Failed to get version code from Google Play from beta track. Track not found: beta.
Delete the edit "03842432596547240246" for the package "io.codemagic.androidhelloworldapp"
Version code info is missing from all tracks
```

### CODE REVIEW

**Comment by craastad** [comment]
Hey @BondarenkoStas what's the status of this PR?

**Comment by priitlatt** [comment]
https://github.com/codemagic-ci-cd/cli-tools/pull/73#issuecomment-790527606
@craastad  It is waiting for my review.

**Comment by BondarenkoStas** [comment]
Just found a bug - need to output request info with logger, not with echo. Will fix in a bit

**Review by mikhail-tokarev — APPROVED** [review]
ready for public release

**Pull request merged**
