### PR TITLE
Feature: Add capabilities to run tests with xcode-project

### PR DESCRIPTION
**Pull request by priitlatt**
**Add support to run iOS tests with `xcode-project`**.

**New actions**:
- [`xcode-project clean`](https://github.com/codemagic-ci-cd/cli-tools/blob/feature/xcode-project-run-tests/docs/xcode-project/clean.md)
- [`xcode-project default-test-destination`](https://github.com/codemagic-ci-cd/cli-tools/blob/feature/xcode-project-run-tests/docs/xcode-project/default-test-destination.md)
- [`xcode-project test-destinations`](https://github.com/codemagic-ci-cd/cli-tools/blob/feature/xcode-project-run-tests/docs/xcode-project/test-destinations.md)
- [`xcode-project junit-test-results`](https://github.com/codemagic-ci-cd/cli-tools/blob/feature/xcode-project-run-tests/docs/xcode-project/junit-test-results.md)
- [`xcode-project run-tests`](https://github.com/codemagic-ci-cd/cli-tools/blob/feature/xcode-project-run-tests/docs/xcode-project/run-tests.md)
- [`xcode-project test-summary`](https://github.com/codemagic-ci-cd/cli-tools/blob/feature/xcode-project-run-tests/docs/xcode-project/test-summary.md)

**Global changes**:
- Simplify access to currently invoked CLI app. Instead of passing around the `CliApp` instance to subsequent function/method calls, add a `RunningCliAppMixin` that can be extended in case a class needs access to currently invoked CLI app.

**Example executions of new nactions**

- Clean Xcode project / workspace
```bash
> xcode-project clean --project banaan.xcodeproj
Clean banaan.xcodeproj
Execute "xcodebuild -project banaan.xcodeproj -scheme banaan clean"

▸ Clean Succeeded
Cleaned banaan.xcodeproj
```

- Show default test destination for currently active Xcode
```bash
> xcode-project default-test-destination
Show default test destination for Xcode 12.0.1 (12A7300)
iOS 14.0 iPhone SE (2nd generation)
```

- List available test destinations for currently active Xcode
```bash
> xcode-project test-destinations --runtime 'iOS 14.0' 'iOS 13.2' --name 'iPhone 11 Pro'                                                                                                                               List available test devices
Runtime: iOS 13.2
- iPhone 11 Pro
- iPhone 11 Pro Max
Runtime: iOS 14.0
- iPhone 11 Pro
- iPhone 11 Pro Max
```

- Convert Xcode test result bundle to JUnit XML
```bash
> xcode-project junit-test-results --xcresult ~/xcode_test_results/Test-banaan-iPhone-11.xcresult
Searching for files matching /Users/priit/xcode_test_results/Test-banaan-iPhone-11.xcresult
Found test results at
- /Users/priit/xcode_test_results/Test-banaan-iPhone-11.xcresult

Saved JUnit XML report to Test-banaan-iPhone-11.xml
```

- Show test result summary for given xcresult
```bash
> xcode-project test-summary -p ~/Library/Developer/Xcode/DerivedData/banaan-*/Logs/Test/Test-banaan-2020.11.05_12-31-44-+0200.xcresult                                                                                  1 ↵
Searching for files matching /Users/priit/Library/Developer/Xcode/DerivedData/banaan-algefjbcdshajvbxwpmdzvoeeavh/Logs/Test/Test-banaan-2020.11.05_12-31-44-+0200.xcresult
Found test results at
- /Users/priit/Library/Developer/Xcode/DerivedData/banaan-algefjbcdshajvbxwpmdzvoeeavh/Logs/Test/Test-banaan-2020.11.05_12-31-44-+0200.xcresult

┌───────────────────────────────────────────────────────────────────────────────────┐
│                                 Testsuite summary                                 │
├─────────────────────────────────────┬─────────────────────────────────────────────┤
│  Name                               │  banaanUITests                              │
│  Device Architecture                │  x86_64                                     │
│  Device Identifier                  │  62A88EE8-78FA-46E0-9717-F7CDE30C525D       │
│  Device Name                        │  iPhone SE (2nd generation)                 │
│  Device Operating System            │  14.1 (18A8394)                             │
│  Device Platform                    │  iOS Simulator                              │
│  Ended Time                         │  2020-11-05T12:32:06                        │
│  Started Time                       │  2020-11-05T12:31:44                        │
│  Title                              │  Testing project banaan with scheme banaan  │
├─────────────────────────────────────┼─────────────────────────────────────────────┤
│  Total tests ran                    │  2                                          │
│  Total tests failed                 │  1                                          │
│  Total tests errored                │  0                                          │
│  Total tests skipped                │  0                                          │
├─────────────────────────────────────┴─────────────────────────────────────────────┤
│                                   Failed tests                                    │
├─────────────────────────────────────┬─────────────────────────────────────────────┤
│  banaanUITests.testUIFailExample()  │  failed - Bad UI                            │
└─────────────────────────────────────┴─────────────────────────────────────────────┘

┌─────────────────────────────┐
│      Test run summary       │
├───────────────────────┬─────┤
│  Test suites          │  1  │
│  Total tests ran      │  2  │
│  Total tests failed   │  1  │
│  Total tests errored  │  0  │
│  Total tests skipped  │  0  │
└───────────────────────┴─────┘
```

- Run Xcode project / workspace tests
```bash
> xcode-project run-tests --project banaan.xcodeproj --test-only banaanUITests --device 'iOS 14.0 iPhone 11'
Running tests on simulators:
- iOS 14.0 iPhone 11 (2B5CD144-D990-4A12-A86E-A95FE03D987B)

Run tests for banaan.xcodeproj

Execute "xcodebuild -project banaan.xcodeproj -scheme banaan -only-testing banaanUITests -sdk iphonesimulator -destination id=2B5CD144-D990-4A12-A86E-A95FE03D987B test"

▸ Linking banaan
▸ Processing Info.plist
▸ Running script 'Run Script'
▸ Processing Info.plist
▸ Processing Info.plist
▸ Linking banaanUITests
▸ Linking banaanTests
All tests
Test Suite banaanUITests.xctest started
banaanUITests
    ✓ testUIExample (2.627 seconds)
    ✗ testUIFailExample, failed - Bad UI


	 Executed 2 tests, with 1 failure (0 unexpected) in 5.514 (5.516) seconds


Test run failed

Found test results at
- /Users/priit/Library/Developer/Xcode/DerivedData/banaan-algefjbcdshajvbxwpmdzvoeeavh/Logs/Test/Test-banaan-2020.11.03_18-31-14-+0200.xcresult

Executed 2 tests with 1 failures and 0 errors in 5.51 seconds.

┌───────────────────────────────────────────────────────────────────────────────────┐
│                                 Testsuite summary                                 │
├─────────────────────────────────────┬─────────────────────────────────────────────┤
│  Name                               │  banaanUITests                              │
│  Device Architecture                │  x86_64                                     │
│  Device Identifier                  │  2B5CD144-D990-4A12-A86E-A95FE03D987B       │
│  Device Name                        │  iPhone 11                                  │
│  Device Operating System            │  14.0 (18A372)                              │
│  Device Platform                    │  iOS Simulator                              │
│  Ended Time                         │  2020-11-03T18:31:55                        │
│  Started Time                       │  2020-11-03T18:31:14                        │
│  Title                              │  Testing project banaan with scheme banaan  │
├─────────────────────────────────────┼─────────────────────────────────────────────┤
│  Total tests ran                    │  2                                          │
│  Total tests failed                 │  1                                          │
│  Total tests errored                │  0                                          │
│  Total tests skipped                │  0                                          │
├─────────────────────────────────────┴─────────────────────────────────────────────┤
│                                   Failed tests                                    │
├─────────────────────────────────────┬─────────────────────────────────────────────┤
│  banaanUITests.testUIFailExample()  │  failed - Bad UI                            │
└─────────────────────────────────────┴─────────────────────────────────────────────┘

┌─────────────────────────────┐
│      Test run summary       │
├───────────────────────┬─────┤
│  Test suites          │  1  │
│  Total tests ran      │  2  │
│  Total tests failed   │  1  │
│  Total tests errored  │  0  │
│  Total tests skipped  │  0  │
└───────────────────────┴─────┘

Saved JUnit XML report to Test-banaan-2020.11.03_18-31-14-+0200.xml
```

### CODE REVIEW

**Comment by mikhail-tokarev** [comment]
1 failing test

**Comment by priitlatt** [comment]
**TODOs**:
- Update version info
- Update changelog

**Comment by priitlatt** [comment]
https://github.com/codemagic-ci-cd/cli-tools/pull/54#issuecomment-721240377

Addressed in c847bbf.

**Comment by priitlatt** [comment]
> **~TODOs~**:
> 
> * ~Update version info~
> * ~Update changelog~
> 
> Edit: [#54 (comment)](https://github.com/codemagic-ci-cd/cli-tools/pull/54#issuecomment-721613936)

Addressed in c847bbf.

**Review by mikhail-tokarev — APPROVED** [review]
LGTM

**Pull request merged**
