### PR TITLE
Improvement: Add graceful handling for undefined App Store Connect model relationships and enumerations

### PR DESCRIPTION
**Pull request by priitlatt**
App Store Connect API can be quite unpredictable with its sudden undocumented API changes. Couple of examples:
- [BundleIdPlatform](https://developer.apple.com/documentation/appstoreconnectapi/bundleidplatform) takes values `UNIVERSAL` and `SERVICES` (fix in #93),
- [Certificate](https://developer.apple.com/documentation/appstoreconnectapi/certificate) has relationship `passTypeId` (fix in #99).

Changes such as these break our strict mapping of API responses to Python objects and as a result full command invokation can fail unexpectedly. To be more flexible about such changes in API responses:
- dynamically initialize only known model relatinoships and log the incident to file,
- in case of undefined enumerations generate new `Enum` definition on the fly with necessary values so that it acts just like the predefined enumeration, and log the incident.

### CODE REVIEW

**Comment by priitlatt** [comment]
Example usage of initializing undefined enums:
```python
In [1]: from codemagic.apple.resources.enums import _ResourceEnum

In [2]: class MyEnum(_ResourceEnum):
   ...:         A = 'A'
   ...: 

In [3]: a, b = MyEnum('A'), MyEnum('B')

In [4]: print(type(a), a)
<enum 'MyEnum'> A

In [5]: print(type(b), b)
<enum 'GracefulMyEnum'> B
```

**Comment by priitlatt** [comment]
Example usage of handling undefined relationship in the case of `SigningCertificate` and `passTypeId`:

```
[11:41:48 28-05-2021] DEBUG cli_app.py:219 > Execute /Users/priit/nevercode/cli-tools/src/codemagic/tools/app_store_connect.py get-certificate XXXXXXXXXX
[11:41:48 28-05-2021] DEBUG cli_app.py:220 > From /Users/priit/nevercode/cli-tools/src/codemagic
[11:41:48 28-05-2021] DEBUG cli_app.py:221 > Using Python 3.7.8 on Darwin 20.3.0
[11:41:48 28-05-2021] DEBUG cli_app.py:222 > ------------------------------------------------------------------------------------------------------------
[11:41:48 28-05-2021] INFO  resource_printer.py:78 > Get Signing Certificate XXXXXXXXXX
[11:41:48 28-05-2021] INFO  api_session.py:32 > >>> GET https://api.appstoreconnect.apple.com/v1/certificates/XXXXXXXXXX None
[11:41:48 28-05-2021] DEBUG api_client.py:70 > Generate new JWT for App Store Connect
[11:41:48 28-05-2021] INFO  api_session.py:22 > <<< 200 {'data': ...}

<<<<<<<<<< Unknown relationship is logged here >>>>>>>>>>
[11:41:48 28-05-2021] WARNING resource.py:189 > Unknown relationship 'passTypeId' for resource 'SigningCertificate'
<<<<<<<<<< >>>>>>>>>>

[11:41:48 28-05-2021] INFO  cli_app.py:88 > -- Signing Certificate --
[11:41:48 28-05-2021] INFO  cli_app.py:88 > Id: XXXXXXXXXX
...
[11:41:48 28-05-2021] DEBUG cli_app.py:230 > ---------------------------------------------------------------------
[11:41:48 28-05-2021] DEBUG cli_app.py:231 > Completed AppStoreConnect get-certificate in 00:00 with status code 0
[11:41:48 28-05-2021] DEBUG cli_app.py:232 > ---------------------------------------------------------------------

**Review by artemii-yanushevskyi — APPROVED** [review]

**Comment by artemii-yanushevskyi** [comment]
What if there would be a new relationship that we would like to add asap. Is there a way for us to know about it’s existence?

**Comment by priitlatt** [comment]
https://github.com/codemagic-ci-cd/cli-tools/pull/100#issuecomment-850462064
That is exactly the main pitfall of this change. No way of knowing that something new is added or we have undefined constants. This is the reason why I did not alter the initialization of `Resource.Attributes` as these are the values that are required for modification and create requests.

**Pull request merged**
