### PR TITLE
Add context to beta test group arguments

### PR DESCRIPTION
**Pull request by jleach**
Added some context to the beta test group so its more clear when it can be used.

### CODE REVIEW

**Comment by priitlatt** [comment]
@jleach, thank you for the contribution! One note though, the markdown docs are all autogenerated using [this script](https://github.com/codemagic-ci-cd/cli-tools/blob/master/doc.py), and in order to make the change persist, and make it available to command line `--help` messages, the actual piece of code where the documentation is declared has to be edited. In case of beta groups, you'd have to edit the description of `BETA_GROUP_NAMES_REQUIRED` argument [here](https://github.com/codemagic-ci-cd/cli-tools/blob/v0.14.1/src/codemagic/tools/_app_store_connect/arguments.py#L942).

**Review by priitlatt — CHANGES_REQUESTED** [review]
@jleach, thank you for the contribution! One note though, the markdown docs are all autogenerated using [this script](https://github.com/codemagic-ci-cd/cli-tools/blob/master/doc.py), and in order to make the change persist, and make it available to command line `--help` messages, the actual piece of code where the documentation is declared has to be edited. In case of beta groups, you'd have to edit the description of `BETA_GROUP_NAMES_REQUIRED` argument [here](https://github.com/codemagic-ci-cd/cli-tools/blob/v0.14.1/src/codemagic/tools/_app_store_connect/arguments.py#L942).

**Comment by jleach** [comment]
@priitlatt Will make the change after the holidays 🎄

**Comment by jleach** [comment]
Created PR # #189 to replace this one with the docs in the correct place.

**Pull request closed without merging**
